# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
# IP: The module: 'design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_g_inst_0 || ORIG_REF_NAME==bd_f60c_g_inst_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/bd_f60c_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_aw_0 || ORIG_REF_NAME==bd_f60c_slot_2_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/bd_f60c_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_w_0 || ORIG_REF_NAME==bd_f60c_slot_2_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/bd_f60c_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_b_0 || ORIG_REF_NAME==bd_f60c_slot_2_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/bd_f60c_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_ar_0 || ORIG_REF_NAME==bd_f60c_slot_2_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/bd_f60c_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_r_0 || ORIG_REF_NAME==bd_f60c_slot_2_r_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_7/bd_f60c_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_aw_0 || ORIG_REF_NAME==bd_f60c_slot_3_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_8/bd_f60c_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_w_0 || ORIG_REF_NAME==bd_f60c_slot_3_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_9/bd_f60c_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_b_0 || ORIG_REF_NAME==bd_f60c_slot_3_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_10/bd_f60c_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_ar_0 || ORIG_REF_NAME==bd_f60c_slot_3_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_11/bd_f60c_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_r_0 || ORIG_REF_NAME==bd_f60c_slot_3_r_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_12/bd_f60c_slot_4_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_aw_0 || ORIG_REF_NAME==bd_f60c_slot_4_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_13/bd_f60c_slot_4_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_w_0 || ORIG_REF_NAME==bd_f60c_slot_4_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_14/bd_f60c_slot_4_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_b_0 || ORIG_REF_NAME==bd_f60c_slot_4_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_15/bd_f60c_slot_4_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_ar_0 || ORIG_REF_NAME==bd_f60c_slot_4_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_16/bd_f60c_slot_4_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_r_0 || ORIG_REF_NAME==bd_f60c_slot_4_r_0} -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
# IP: The module: 'design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_g_inst_0 || ORIG_REF_NAME==bd_f60c_g_inst_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/bd_f60c_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_aw_0 || ORIG_REF_NAME==bd_f60c_slot_2_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/bd_f60c_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_w_0 || ORIG_REF_NAME==bd_f60c_slot_2_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/bd_f60c_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_b_0 || ORIG_REF_NAME==bd_f60c_slot_2_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/bd_f60c_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_ar_0 || ORIG_REF_NAME==bd_f60c_slot_2_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/bd_f60c_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_2_r_0 || ORIG_REF_NAME==bd_f60c_slot_2_r_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_7/bd_f60c_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_aw_0 || ORIG_REF_NAME==bd_f60c_slot_3_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_8/bd_f60c_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_w_0 || ORIG_REF_NAME==bd_f60c_slot_3_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_9/bd_f60c_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_b_0 || ORIG_REF_NAME==bd_f60c_slot_3_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_10/bd_f60c_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_ar_0 || ORIG_REF_NAME==bd_f60c_slot_3_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_11/bd_f60c_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_3_r_0 || ORIG_REF_NAME==bd_f60c_slot_3_r_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_12/bd_f60c_slot_4_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_aw_0 || ORIG_REF_NAME==bd_f60c_slot_4_aw_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_13/bd_f60c_slot_4_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_w_0 || ORIG_REF_NAME==bd_f60c_slot_4_w_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_14/bd_f60c_slot_4_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_b_0 || ORIG_REF_NAME==bd_f60c_slot_4_b_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_15/bd_f60c_slot_4_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_ar_0 || ORIG_REF_NAME==bd_f60c_slot_4_ar_0} -quiet] -quiet

# IP: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_16/bd_f60c_slot_4_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_4_r_0 || ORIG_REF_NAME==bd_f60c_slot_4_r_0} -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc

# XDC: d:/Kishore_Sir_Project/dma_testing/dma_testing.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
